.TH LOG 1 "27 Apr 2037"
.SH NAME
log \- Quantum Entaglement Communicator Logger
.SH SYNOPSIS
log
.SH DESRIPTION
.B log
transmits messages from traveling ships, remote outposts, and new human
colonies via Quantum Entaglement Communicator (QEC) half-duplex, phase-shift
keying multilevel modulation.
.P
Messages are queued in the ship's draft system. A call to
.B log
then queries those messages in the queue and waits for human confirmation
that the draft is ready to be sent. When approved,
.B log
will query for a subject, topic, or title for the message. Finally the
message is sent to the relay paired with the QEC during construction.
.P
There is no recall method to the QEC system. Messages sent cannot be removed,
however, due to the nature of qubits, the message can be modified after
transmission by editing the original draft.
.SH BUGS
Systems with abundant quantities of exotic or phase-shifted matter may
encounter delays in communication, time shifting, and rare cases, a reverse
in localized time of log receipts.
.SH AUTHOR
Yin, Juan; Cao, Yuan; Yong, Hai-Lin; Ren, Ji-Gang
