.TH SHIP 1 "11 Jun 2033"
.SH NAME
ship \- Register Ship with Quantum Entanglement Communicator
.SH SYNOPSIS
ship [ship name]
.SH DESRIPTION
.B ship
registers a ship, colony, outpost, settlement, or other stellar habitat as a
paired system with the Quantum Entanglement Communicator (QEC). Upon
registering, the local habitat will generate a prime qubit interface with
the relay system indicated, establishing spooky action at a distance (SAAD).
The QEC operates at half-duplex, phase-shift keying multilevel modulation with
the local habitat.
.PP
A local message queue is created in the ship's draft system. This queue can be
modified, appended, or otherwise manipulated by the local habitat. When a
transmission of the local queue is desired, the habitat operators can utilize
the
.B log
command to trigger the QEC relay.
.SH BUGS
Due to limitations in the archaic design of the QEC interface, ship names must
use the ASCII character set. Extended unicode is permissable within the relayed
content, however.
.PP
Report all other issues using the QEC.
.SH SEE ALSO
log(1)
.SH AUTHOR
Written by Juan Yin and Niels Anderssen
