---
kind: pipeline
name: shellcheck

steps:
    - name: shellcheck
      image: koalaman/shellcheck-alpine:stable
      commands:
          - shellcheck bin/*
          - shellcheck efingerd/*
          - shellcheck completion/*
          - shellcheck update-motd/*
