#!/bin/sh

run_user=$(id -u)
if [ "$run_user" -eq 0 ]; then
  file_html="/var/www/html/index.html"

  # Add header info to html output
  {
  cat > /dev/stdout << END
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="shrink-to-fit=no,width=device-width,height=device-height,initial-scale=1,user-scalable=0,minimum-scale=1,maximum-scale=1">
    <meta name=msapplication-TileColor content=#ffffff>
    <meta name=theme-color content=#ffffff>
    <title>Cosmic Voyage</title>
    <link rel=”canonical” href=”https://cosmic.voyage”>
    <link rel="alternate" type="application/rss+xml" title="Cosmic Voyage" href="/rss.xml">
  </head>
  <body>
    <div id="page-wrapper">
END
  } > "${file_html}"

  # Add intro text
  printf "<div class=\"intro\"><pre>" >> "${file_html}"
  cat "/var/gopher/intro.gophermap" >> "${file_html}"
  printf "</pre></div>" >> "${file_html}"

  # Loop through listings gophermap
  printf "<div class=\"listings\"><pre>" >> "${file_html}"
  printf "Transmission log (newest first):\\n" >> "${file_html}"
  while read -r line; do
    log=$(printf "%s" "$line" | awk -F'\t' '{print $2}')
    title=$(printf "%s" "$line" | awk -F'\t' '{print $1}' | sed 's|^.||')
    {
      printf "<a href=\"%s\">%s</a>\\n" "$log" "$title"
    } >> "${file_html}"
  done < "/var/gopher/listing.gophermap"
  printf "</pre></div>" >> "${file_html}"

  # close up the footer
  {
    printf "</div></body></html>"
  } >> "${file_html}"
else
  printf "You must be root to run this script.\\n"
fi
