#!/bin/sh

run_user=$(id -u)
if [ "$run_user" -eq 0 ]; then
  n="$1"
  s="$2"
  if [ ! -z "$n" ]; then
    user_exists=$(id -u "${n}" 2> /dev/null)
    if [ ! -z "${user_exists}" ]; then
      if [ ! -z "${s}" ]; then
        printf "Creating ship '%s' for user '%s'\\n" "${s}" "${n}"
      else
        printf "Specificy a ship or colony name.\\n"
      fi
    else
      printf "User not found.\\n"
    fi
  else
    printf "Specify a user.\\n"
  fi
else
  printf "You must be root to run this script.\\n"
fi
