#!/bin/sh

run_user=$(id -u)
if [ "$run_user" -eq 0 ]; then
  file_html="/var/www/html/index.html"

  # Add header info to html output
  {
  cat > /dev/stdout << END
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="shrink-to-fit=no,width=device-width,height=device-height,initial-scale=1,user-scalable=1">
    <meta name=msapplication-TileColor content=#ffffff>
    <meta name=theme-color content=#ffffff>
    <title>Cosmic Voyage</title>
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono" rel="stylesheet">
    <link rel="canonical" href="https://cosmic.voyage">
    <link rel="alternate" type="application/rss+xml" title="Cosmic Voyage" href="/rss.xml">
    <style>
      body, html {
        color: rgb(62, 231, 123);
        background-color: #000;
        font-size: 12px;
      }

      a, a:visited, a:hover, a:active {
        color: rgb(62, 231, 123);
      }

      .page-wrapper {
        text-align: center;
      }

      .inner-wrapper {
        display: inline-block;
        text-align: left;
        white-space: pre;
        font-family: 'IBM Plex Mono', monospace;
        margin: 0 auto;
        width: auto;
      }

      @media screen and (min-width: 700px) {
        body, html {
          font-size: 16px;
        }
      }
    </style>
  </head>
  <body>
    <div class="page-wrapper">
    <div class="inner-wrapper">
END
  } > "${file_html}"

  # Add intro text
  cat "/var/gopher/intro.gophermap" >> "${file_html}"

  # Loop through listings gophermap
  printf "\\n\\nTransmission log (newest first):\\n" >> "${file_html}"
  while read -r line; do
    log=$(printf "%s" "$line" | awk -F'\t' '{print $2}')
    loghtml=$(printf "%s" "$log" | sed 's/\.[^.]*$//')
    logdir=$(dirname "$log")
    title=$(printf "%s" "$line" | awk -F'\t' '{print $1}' | sed 's|^.||')
    # print link in listings
    printf "<a href=\"%s.html\">%s</a>\\n" "$loghtml" "$title" >> "${file_html}"

    # create entry
    entry_html="/var/www/html${loghtml}.html"
    mkdir -p "/var/www/html${logdir}"
    {
      cat > /dev/stdout << ENTRY
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="shrink-to-fit=no,width=device-width,height=device-height,initial-scale=1,user-scalable=1">
    <meta name=msapplication-TileColor content=#ffffff>
    <meta name=theme-color content=#ffffff>
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono" rel="stylesheet">
    <style>
      body, html {
        color: rgb(62, 231, 123);
        background-color: #000;
        font-size: 12px;
      }

      a, a:visited, a:hover, a:active {
        color: rgb(62, 231, 123);
      }

      .page-wrapper {
        text-align: center;
      }

      .inner-wrapper {
        display: inline-block;
        text-align: left;
        white-space: pre;
        font-family: 'IBM Plex Mono', monospace;
        margin: 0 auto;
        width: auto;
      }

      @media screen and (min-width: 700px) {
        body, html {
          font-size: 16px;
        }
      }
    </style>
ENTRY
    } > "${entry_html}"

    {
      printf "    <title>%s</title>\\n" "$title"
      printf "    <link rel=\"canonical\" href=\"https://cosmic.voyage%s.html\">\\n" "$loghtml"

      printf "</head>\\n<body>\\n<div class=\"page-wrapper\"><div class=\"inner-wrapper\">\\n"
      printf "<a href="/">&lt;&lt;&lt; BACK TO RELAY ONE</a>\\n\\n\\n"
      cat "/var/gopher${log}"
      # close up the entry footer
      printf "</div></div></body></html>"
    } >> "${entry_html}"

  done < "/var/gopher/listing.gophermap"
  printf "</div>" >> "${file_html}"

  # close up the footer
  {
    printf "</div></body></html>"
  } >> "${file_html}"
else
  printf "You must be root to run this script.\\n"
fi
