#!/bin/sh

user=$(whoami)
ships=$(find /var/gopher -user "$user" -type d -exec basename {} \;)
numships=$(echo "${ships}" | wc -l)
printf "Initializing QEC...\\n\\n"
printf "Ready to transmit for %s\\n" "${user}"
if [ "$numships" -eq 0 ]; then
  printf "No ships found in system.\\n"
elif [ "$numships" -eq 1 ]; then
  printf "Ship found: %s\\n" "${ships}"
else
  printf "Multiple ships found: %s\\n" "${ships}"
fi

# look at log entries in gophermap
# compare against files in ship directory
# store list of unpublished logs
logs=$(grep "^[01]$ships" "/var/gopher/gophermap" | awk -F'\t' '{print $2}')
files=$(find "/var/gopher/$ships" -type f | sed 's|/var/gopher||')
uniq=$(printf "%s\\n%s" "$logs" "$files" | uniq -u)

printf "uniques: %s\\n" "$uniq"
